
version: '3.8'

services:
  fastapi-app:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv  # Exclude .venv from volume mount
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["uv", "run", "src/main.py"]