name: Lint

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: make install

      - name: Run linters
        run: make lint


