name: Lint

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.12'

      - name: Sync dependencies
        run: make install

      - name: Run linters
        run: make lint


